"""Helpers for durable in-app notifications generated by the OT workflow."""

from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.notification import Notification
from app.models.user import User, UserRole
from app.models.work_order import WorkOrder
from app.models.supervisor_area import supervisor_areas


async def create_notification(
    db: AsyncSession,
    *,
    user_id: int,
    type: str,
    message: str,
    link: str | None = None,
) -> Notification:
    """Insert and flush one notification inside the current OT transaction."""
    notification = Notification(user_id=user_id, type=type, message=message, link=link)
    db.add(notification)
    await db.flush()
    return notification


def _assigned_recipient_ids(
    wo: WorkOrder, participant_user_ids: list[int] | None = None
) -> set[int]:
    recipients: set[int] = set()
    if wo.responsible_user_id is not None:
        recipients.add(wo.responsible_user_id)
    if wo.coordinator_user_id is not None:
        recipients.add(wo.coordinator_user_id)
    if participant_user_ids is not None:
        recipients.update(participant_user_ids)
    else:
        try:
            recipients.update(participant.id for participant in (wo.participants or []))
        except Exception:
            pass
    return recipients


async def _admin_ids(db: AsyncSession) -> set[int]:
    result = await db.execute(
        select(User.id).where(
            User.is_active.is_(True),
            User.role == UserRole.ADMIN,
        )
    )
    return {row[0] for row in result.all()}


async def _notify_users(
    db: AsyncSession,
    user_ids: set[int],
    *,
    wo: WorkOrder | None = None,
    type: str,
    message: str,
    link: str | None,
    exclude_user_id: int | None = None,
) -> None:
    if wo is not None and user_ids:
        # Supervisors follow only the OTs they emitted. This prevents a
        # supervisor from receiving assignment/lifecycle notifications for an
        # OT created by an administrator or another supervisor.
        result = await db.execute(
            select(User.id, User.role).where(User.id.in_(user_ids))
        )
        roles = {row[0]: row[1] for row in result.all()}
        user_ids = {
            user_id
            for user_id in user_ids
            if roles.get(user_id) != UserRole.SUPERVISOR
            or user_id == wo.created_by_user_id
        }
    for user_id in user_ids:
        if user_id != exclude_user_id:
            await create_notification(
                db, user_id=user_id, type=type, message=message, link=link
            )


async def notify_work_order_assigned(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    link: str,
    participant_user_ids: list[int] | None = None,
) -> None:
    await _notify_users(
        db,
        _assigned_recipient_ids(wo, participant_user_ids),
        wo=wo,
        type="OT_ASIGNADA",
        message=f"Nueva OT {wo.ot_number} asignada a usted.",
        link=link,
    )


async def notify_work_order_submitted_to_admin(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    submitted_by: str,
    link: str,
) -> None:
    """Tell administrators that a supervisor emitted an OT for review."""
    await _notify_users(
        db,
        await _admin_ids(db),
        wo=wo,
        type="OT_EMITIDA",
        message=f"{submitted_by} emitió la OT {wo.ot_number}; está pendiente de gestión.",
        link=link,
    )


async def notify_work_order_reassigned(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    previous_recipient_ids: set[int],
    participant_user_ids: list[int] | None,
    link: str,
    actor_user_id: int | None = None,
) -> None:
    current = _assigned_recipient_ids(wo, participant_user_ids)
    await _notify_users(
        db,
        current - previous_recipient_ids,
        wo=wo,
        type="OT_REASIGNADA",
        message=f"OT {wo.ot_number} fue reasignada a usted.",
        link=link,
        exclude_user_id=actor_user_id,
    )
    await _notify_users(
        db,
        previous_recipient_ids - current,
        wo=wo,
        type="OT_REASIGNADA",
        message=f"OT {wo.ot_number} ya no está asignada a usted.",
        link=link,
        exclude_user_id=actor_user_id,
    )


async def notify_work_order_completed(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    performer = wo.completed_by_user.full_name if wo.completed_by_user else "El trabajador"
    await _notify_users(
        db,
        # Administrators need to know about every completed OT. A supervisor
        # must only receive the completion notification for an OT that they
        # emitted, so do not broadcast this event to all supervisors.
        {wo.created_by_user_id} | await _admin_ids(db),
        wo=wo,
        type="OT_COMPLETADA",
        message=f"OT {wo.ot_number} finalizada por {performer}, pendiente de aprobación.",
        link=link,
        exclude_user_id=exclude_user_id,
    )


async def notify_supervisor_validation_pending(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    """Notify every active supervisor assigned to the OT's area.

    This intentionally does not use ``_notify_users`` because supervisors
    normally receive only their own emitted OT notifications. Validation is a
    shared area responsibility, so all eligible supervisors must be informed.
    """
    assigned_area_supervisors = await db.execute(
        select(User.id).where(
            User.is_active.is_(True),
            User.role == UserRole.SUPERVISOR,
            or_(
                User.area_id == wo.area_id,
                User.id.in_(
                    select(supervisor_areas.c.supervisor_id).where(
                        supervisor_areas.c.area_id == wo.area_id
                    )
                ),
            ),
        )
    )
    for (user_id,) in assigned_area_supervisors.all():
        if user_id != exclude_user_id:
            await create_notification(
                db,
                user_id=user_id,
                type="OT_VALIDACION_SUPERVISOR",
                message=f"La OT {wo.ot_number} finalizó y requiere validación de un supervisor del área.",
                link=link,
            )


async def notify_supervisor_reviewed(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    approved: bool,
    reviewer_name: str,
    notes: str | None = None,
    link: str | None = None,
) -> None:
    suffix = f" Motivo: {notes}" if notes and not approved else ""
    message = (
        f"{reviewer_name} validó la OT {wo.ot_number}; ya puede ser aprobada por el administrador."
        if approved
        else f"{reviewer_name} devolvió la OT {wo.ot_number} al trabajador para corrección.{suffix}"
    )
    await _notify_users(
        db,
        {wo.created_by_user_id} | await _admin_ids(db) | _assigned_recipient_ids(wo),
        wo=wo,
        type="OT_VALIDADA_SUPERVISOR" if approved else "OT_DEVUELTA_SUPERVISOR",
        message=message,
        link=link,
    )


async def notify_work_order_approved(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    await _notify_users(
        db,
        _assigned_recipient_ids(wo) | {wo.created_by_user_id},
        wo=wo,
        type="OT_APROBADA",
        message=f"OT {wo.ot_number} aprobada y cerrada.",
        link=link,
        exclude_user_id=exclude_user_id,
    )


async def notify_work_order_returned(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    reason: str,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    suffix = f" Motivo: {reason}" if reason else ""
    await _notify_users(
        db,
        _assigned_recipient_ids(wo) | {wo.created_by_user_id},
        wo=wo,
        type="OT_DEVUELTA",
        message=f"OT {wo.ot_number} devuelta para corrección.{suffix}",
        link=link,
        exclude_user_id=exclude_user_id,
    )


async def notify_work_order_cancelled(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    reason: str,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    suffix = f" Motivo: {reason}" if reason else ""
    await _notify_users(
        db,
        _assigned_recipient_ids(wo) | {wo.created_by_user_id},
        wo=wo,
        type="OT_CANCELADA",
        message=f"OT {wo.ot_number} fue cancelada.{suffix}",
        link=link,
        exclude_user_id=exclude_user_id,
    )


async def notify_work_order_reopened(
    db: AsyncSession,
    wo: WorkOrder,
    *,
    reason: str,
    link: str | None = None,
    exclude_user_id: int | None = None,
) -> None:
    state = "en proceso" if wo.status == "IN_PROGRESS" else "como borrador"
    await _notify_users(
        db,
        _assigned_recipient_ids(wo) | {wo.created_by_user_id},
        wo=wo,
        type="OT_REABIERTA",
        message=f"OT {wo.ot_number} fue reabierta {state}. Motivo: {reason}",
        link=link,
        exclude_user_id=exclude_user_id,
    )
