export const WORK_ORDER_AREAS = [
  "CEBADA",
  "MALTA",
  "PLANTA EXTRACTO",
  "PLANTA CAJON",
  "RECEPCION Y DESPACHO",
  "ADMINISTRACION",
  "SEMILLA",
  "MANTENCION",
  "PAÑOL",
  "CONTROL DE CALIDAD",
] as const;
